version: '3.9'
services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: "2565"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/assessment?sslmode=disable"
    ports:
      - "2565:2565"
    expose:
      - "2565"
    depends_on:
      - db

  db:
    image: postgres:11
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assessment
    restart: on-failure
